# configs/dialect_badou.yaml
phonetic_rules:
  e: ɛ
  o: ɔ

lexical_variants:
  ananas: ababil
  fusil: abětů
  renard: abeyí

tonal_rules:
  sandhi:
    - pattern: "bă(.*)bá"
      replacement: "bà\1bá"
  exceptions:
    - akpé
    - nukpó